#!/usr/bin/env python3
"""Write docs/COUNTRIES.md: what Beranda covers, country by country, for every continent.

Generated from the code (countries table, holiday data, news catalog) so it never drifts:
    python scripts/countries_doc.py
"""

from __future__ import annotations

from pathlib import Path

import holidays
from holidays.registry import COUNTRIES as HOLIDAY_REGISTRY

from beranda.config import SUNDAY_FIRST
from beranda.providers import countries, news_catalog
from beranda.providers.specialdays import holiday_language

LANGUAGE_NAMES = {
    "en": "English", "fr": "French", "de": "German", "es": "Spanish", "it": "Italian",
    "pt": "Portuguese", "pt-BR": "Brazilian Portuguese", "nl": "Dutch", "ca": "Catalan",
    "da": "Danish", "sv": "Swedish", "nb": "Norwegian", "fi": "Finnish", "pl": "Polish",
    "cs": "Czech", "sk": "Slovak", "sl": "Slovenian", "hr": "Croatian", "sr": "Serbian",
    "bg": "Bulgarian", "ro": "Romanian", "hu": "Hungarian", "el": "Greek", "lt": "Lithuanian",
    "lv": "Latvian", "et": "Estonian", "uk": "Ukrainian", "ru": "Russian", "tr": "Turkish",
    "ar": "Arabic", "he": "Hebrew", "fa": "Persian", "ur": "Urdu", "hi": "Hindi", "bn": "Bengali",
    "zh": "Chinese (simplified)", "zh-TW": "Chinese (traditional)", "ja": "Japanese",
    "ko": "Korean", "th": "Thai", "vi": "Vietnamese", "ms": "Malay", "id": "Indonesian",
    "tl": "Filipino", "sw": "Swahili", "am": "Amharic", "af": "Afrikaans", "ht": "Haitian Creole",
    "ha": "Hausa", "yo": "Yoruba", "zu": "Zulu", "so": "Somali", "mg": "Malagasy", "wo": "Wolof",
    "ta": "Tamil", "ty": "Tahitian", "qu": "Quechua",
}
RTL = {"ar", "he", "fa", "ur"}
# Countries the holidays library does not name (territories) or names awkwardly.
EXTRA_NAMES = {
    "CI": "Côte d'Ivoire", "CD": "Congo (DR)", "CG": "Congo", "KP": "Korea (North)",
    "KR": "Korea (South)", "GB": "United Kingdom", "US": "United States", "RE": "Réunion",
    "YT": "Mayotte", "SH": "Saint Helena", "BL": "Saint Barthélemy", "MF": "Saint Martin",
    "PM": "Saint Pierre and Miquelon", "TL": "Timor-Leste", "PS": "Palestine", "XK": "Kosovo",
    "EH": "Western Sahara", "CX": "Christmas Island", "CC": "Cocos Islands",
}
REGION_ORDER = ("europe", "north_america", "latam", "africa", "middle_east", "asia", "oceania")


def name_of(code: str) -> str:
    if code in EXTRA_NAMES:
        return EXTRA_NAMES[code]
    for key, entry in HOLIDAY_REGISTRY.items():
        if entry[1] == code:
            return key.replace("_", " ").title()
    return code


def holiday_cell(code: str) -> str:
    try:
        holidays.country_holidays(code, years=2026)
    except NotImplementedError:
        return "–"
    lang = holiday_language(code, countries.suggested_language(code))
    return f"yes ({lang})" if lang else "yes"


def news_cell(code: str) -> str:
    mine = [s["name"] for s in news_catalog.national(code)]
    if mine:
        return ", ".join(mine)
    region = countries.REGION_OF.get(code)
    first = countries.suggested_language(code).split("-")[0]
    regional = [s for s in news_catalog.SOURCES if s.get("region") == region]
    regional = [s["name"] for s in sorted(regional, key=lambda s: s["lang"] != first)]
    return "regional: " + ", ".join(regional[:2]) if regional else "international"


def table(codes: list[str]) -> list[str]:
    rows = ["| Country | Code | Display language(s) | Public holidays (names in) | Week starts | Preset news |",
            "|---|---|---|---|---|---|"]
    for code in sorted(codes, key=name_of):
        langs = ", ".join(countries.COUNTRY_LANGUAGES[code])
        start = "Sunday" if code in SUNDAY_FIRST else "Monday"
        rows.append(f"| {name_of(code)} | {code} | {langs} | {holiday_cell(code)} | {start} | {news_cell(code)} |")
    return rows


def main() -> None:
    by_region: dict[str, list[str]] = {r: [] for r in REGION_ORDER}
    for code, region in countries.REGION_OF.items():
        by_region[region].append(code)
    langs = ", ".join(f"{LANGUAGE_NAMES[c]}{' (right to left)' if c in RTL else ''} `{c}`" for c in countries.LANGUAGES)
    lines = [
        "# Countries and languages",
        "",
        "*Generated by `scripts/countries_doc.py` from the code itself.*",
        "",
        (
            f"Beranda knows **{len(countries.REGION_OF)} countries and territories** on every continent, "
            f"and speaks **{len(countries.LANGUAGES)} languages**. Weather, moon, sun, town search and"
        ),
        "\"news about my town\" work everywhere. What changes from one country to another:",
        "",
        "- **Display language(s)**: the first one is suggested when you pick the country; any",
        "  language can be chosen anywhere. Where Beranda does not speak the local language yet,",
        "  the language people commonly read there is suggested (often English or French).",
        "- **Public holidays**: from the open-source `holidays` library; in brackets, the language of",
        "  the holiday names with the suggested display language.",
        "- **Preset news**: media Beranda proposes. \"regional\" means continental media are proposed",
        "  instead; you can add any RSS feed yourself in every country.",
        "",
        f"**Languages**: {langs}.",
        "",
        "The settings page itself is in English, French, German, Spanish, Italian, Portuguese,",
        "Brazilian Portuguese, Indonesian, Arabic and Swahili; for the other languages it shows",
        "English while the screen speaks your language.",
        "",
        "Not translated yet (contributions welcome, one JSON file each): Kinyarwanda, Nepali,",
        "Khmer, Lao, Burmese, Sinhala, Georgian, Armenian, Azerbaijani, Kazakh, Uzbek, Mongolian,",
        "Albanian, Macedonian, Icelandic, Irish, Maltese, Māori, Samoan, Tongan, Fijian, Guarani.",
        "",
    ]
    for region in REGION_ORDER:
        lines += [f"## {countries.REGION_NAMES[region]}", "", *table(by_region[region]), ""]
    out = Path(__file__).resolve().parent.parent / "docs" / "COUNTRIES.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", out, len(countries.REGION_OF), "countries")


if __name__ == "__main__":
    main()
